// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoNUvOJtuW5EdQXuqaxAUzBCwCv7qGHdM',
    appId: '1:947057387608:web:577f2f6f95d8b2b159422d',
    messagingSenderId: '947057387608',
    projectId: 'verde-1481b',
    authDomain: 'verde-1481b.firebaseapp.com',
    storageBucket: 'verde-1481b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAygTY4C2bunh4uqj2mq3eg6qZvDM03cuQ',
    appId: '1:947057387608:android:970674c21aded08b59422d',
    messagingSenderId: '947057387608',
    projectId: 'verde-1481b',
    storageBucket: 'verde-1481b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8tBk8u9BgeWmUy2aTWyW2D0x6DV5lLpM',
    appId: '1:947057387608:ios:1b022b55bc8af1fa59422d',
    messagingSenderId: '947057387608',
    projectId: 'verde-1481b',
    storageBucket: 'verde-1481b.firebasestorage.app',
    iosBundleId: 'com.example.softengProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8tBk8u9BgeWmUy2aTWyW2D0x6DV5lLpM',
    appId: '1:947057387608:ios:1b022b55bc8af1fa59422d',
    messagingSenderId: '947057387608',
    projectId: 'verde-1481b',
    storageBucket: 'verde-1481b.firebasestorage.app',
    iosBundleId: 'com.example.softengProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoNUvOJtuW5EdQXuqaxAUzBCwCv7qGHdM',
    appId: '1:947057387608:web:59be7b8f68845a4859422d',
    messagingSenderId: '947057387608',
    projectId: 'verde-1481b',
    authDomain: 'verde-1481b.firebaseapp.com',
    storageBucket: 'verde-1481b.firebasestorage.app',
  );
}
